### ISSUE TITLE
Philips 3259/10 

### ISSUE THREAD

**Issue by AcidSleeper** [xMrVizzy/Philips-AirPurifier#1]
Hey

I followed the instructions and the fan appeares in Hassio.
Put directly on restart of Hassio I hear a sound from the Philips 3259/10. The sound continues to play every 30 seconds, like “ding, ding, ding”.
I dont get any errors i Hassio except the varning about custom integration. What is making the sound?

My Philips 3259 dont have temperature, humidity, water or wick-filter and I also see “function: null” that I apparently dont have.

Another problem: I set the light to OFF/Zero in the mobileapp, Hassio dont register the change until the “30-seconds sound” and Im getting Zero in state light_brightness but Hassio turns the light back on and after another “30-seconds sound” it changes the state back to 100.

I think something is not working with Philips 3259. What to do?
If I remove the code for the fan, Philips 3259 stop acting strange.

Ronald has the same problem and the Idea that 
the “beeps” normally occur when the philips app sends a status change. He thought it could be the app and the home assistant plugin conflict with each other?

I downloaded Wireshark and added Philips as a filter.
Alot of whois as expected
When I change the setting on the app - Wireshark No. 28549-28551 and under Info: 8080 --> 8080 Len=326

“Something” seems to send settings every 30seconds. No. 2993-2996 and under Info: 8080 --> 8080 Len=387 and alot of others in 30seconds gap.

Do someone want to have a look at the saved wireshark-file?
I dont have the knowledge to analyze it.

Can send it or upload somewhere.

**Comment by AcidSleeper** [comment]
Latest update didnt resolve this issue.

**Comment by AcidSleeper** [comment]
Now its working

**Comment by xMrVizzy** [comment]
Awesome!

**Comment by ronaldt80** [comment]
Fantastic tool! No more beeps also on my end.
