### ISSUE TITLE
AC2729/10 switched to COAP protocol

### ISSUE THREAD

**Issue by Wicket2778** [xMrVizzy/philips-airpurifier#11]
it appears that philips has moved the AC2729/10 to COAP protocol.
Reference [https://github.com/rgerganov/py-air-control/issues/21]

Any way possible to change code? I have too little knowledge to do changes myself

**Comment by regnets** [comment]
I think all air purifiers are going to switch to the COAP protocol. I just purchased an AC3259/10 which is also unable to control with py-air-control.
