### ISSUE TITLE
Philips 4000i

### ISSUE THREAD

**Issue by muchar** [xMrVizzy/philips-airpurifier#13]
Is there any possibility that this plugin will work with Philips Air Purifier from the series 4000i?

**Comment by spider7611** [comment]
Need this too. I have the sam type Philips Air Purifier.

**Comment by xMrVizzy** [comment]
Should work now

**Comment by spider7611** [comment]
Tried it but isn't working. :(

**Comment by GeorgeSG** [comment]
@xMrVizzy I think the series 4000 are some of the newer devices that use CoAP instead of HTTP for communication. If it is - it won't work.

I know [rgerganov/py-air-control](github.com/rgerganov/py-air-control) has some experimental stuff for that, but I have no way to test it.
