### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by BigFam194** [xMrVizzy/philips-airpurifier#26]
From Home Assistant Log:

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 2:59:07 PM (1 occurrences)
Last logged: 2:59:07 PM

No 'version' key in the manifest file for custom integration 'philips_airpurifier'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'philips_airpurifier'

**Comment by ekeih** [comment]
With the current (2021.4.x) version of home assistant the message gets even more specific: It will break with 2021.6.

```
No 'version' key in the manifest file for custom integration 'philips_airpurifier'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'philips_airpurifier'
```
