### ISSUE TITLE
fan.set_speed no longer words

### ISSUE THREAD

**Issue by superman3** [xMrVizzy/philips-airpurifier#8]
updated to 3.6
changed the platform config from philips_airpurifier to philips-airpurifier to get it working again but fan.set_speed no longer works

I had a script that turned on the fan and set it Allergen mode - fan switches on but never changes mode :(

**Comment by superman3** [comment]
wonder if its because of this issue - the AC2889 requires both manual mode and fan speed set in one command - 

https://github.com/rgerganov/py-air-control/issues/16

**Comment by superman3** [comment]
also noticed 'M': 'Manual', 'B': 'Bacteria', 'N': 'Night' are listed in the speed list but not in the set list, i would add them in by a PR req but as i cant set the speed at the moment to say allergen mode which is listed i cant test any of them

**Comment by superman3** [comment]
reinstalled and if i ran fan.turn_on with

entity_id: fan.philips_airpurifier
speed: Allergen Mode

it works

but fan.turn_on and then fan.set_speed seperatly doesnt

**Comment by superman3** [comment]
in the end to get this working i had to have a script that did:

action1
fan.turn_on
entity_id: fan.philips_airpurifier
action2
fan.turn_on
entity_id: fan.philips_airpurifier
speed: Allergen Mode

adding the speed into action1 never seemed to work

**Comment by robroll** [comment]
It is because the code doesn't define set_speed as a supported feature.

@property
    def supported_features(self) -> int:
        """Flag supported features."""
        return SUPPORT_SET_SPEED
